<Project>
  <PropertyGroup>
    <SolutionName Condition="'$(SolutionName)' == ''">shared</SolutionName>

    <RootOutputPath Condition="'$(LDBUILD_OUTPUT_ROOT)' == ''">
      $(MSBuildThisFileDirectory)Output/$(SolutionName)/</RootOutputPath>
    <RootOutputPath Condition="'$(LDBUILD_OUTPUT_ROOT)' != ''">
      $(LDBUILD_OUTPUT_ROOT)/$(SolutionName)/</RootOutputPath>

    <BaseOutputPath>$(RootOutputPath)bin/$(MSBuildProjectName)</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RootOutputPath)obj/$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <PublishDir>$(RootOutputPath)publish/$(MSBuildProjectName)</PublishDir>

    <RuntimeIdentifier Condition="'$(LDBUILD_TARGET_RUNTIME)' != ''">$(LDBUILD_TARGET_RUNTIME)</RuntimeIdentifier>

    <ShouldUnsetParentConfigurationAndPlatform>false</ShouldUnsetParentConfigurationAndPlatform>

    <IsPackable>False</IsPackable>
    <IsPublishable>False</IsPublishable>

    <RunSettingsFilePath>$(MSBuildThisFileDirectory)\.runsettings</RunSettingsFilePath>
  </PropertyGroup>
</Project>